repositories = [ "mavenCentral" ]
pluginRepositories = [ "mavenCentral", "gradlePluginPortal" ]
cacheDir = "build/cache/caupain"
outputType = "markdown"
outputPath = "build/reports/dependency-updates.md"
showVersionReferences = true
gradleStabilityLevel = "stable"
searchReleaseNote = true