repositories = [ "mavenCentral" ]
pluginRepositories = [ "mavenCentral", "gradlePluginPortal" ]
cacheDir = "build/cache/caupain"
outputTypes = [ "markdown", "html", "console" ]
showVersionReferences = true
gradleStabilityLevel = "stable"
searchReleaseNote = true